version: '3.9'

services:
  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mlh_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    network_mode: host
    volumes:
      - .:/app
    environment:
      - DEBUG=True
      - USE_POSTGRES=True
      - DB_ENGINE=django.db.backends.postgresql
      - DB_NAME=postgres
      - DB_USER=postgres.pvdvmqufmafmszarxuvv
      - DB_PASSWORD=cuf1cgj*jze1jdf*UWK
      - DB_HOST=aws-0-us-west-2.pooler.supabase.com
      - DB_PORT=5432
      - DB_SSLMODE=require

volumes:
  postgres_data:
