# Generated by Django 5.0.9 on 2025-12-06 04:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PersonalityTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("icon", models.CharField(blank=True, help_text="Icon name/emoji", max_length=50)),
                (
                    "color",
                    models.CharField(default="#6366f1", help_text="Hex color code", max_length=7),
                ),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "db_table": "personality_traits",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="is_email_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_phone_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="location_visibility",
            field=models.CharField(
                choices=[
                    ("exact", "Exact Location"),
                    ("approximate", "Approximate (within 1km)"),
                    ("hidden", "Hidden"),
                ],
                default="approximate",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="user",
            name="share_location",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="total_reviews",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="trust_score",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=3,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(5),
                ],
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name="UserPersonalityTrait",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "prominence_score",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="How prominent this trait is (1-5)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "personality_trait",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="users.personalitytrait"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_personality_traits",
                "unique_together": {("user", "personality_trait")},
            },
        ),
        migrations.AddField(
            model_name="user",
            name="personality_traits",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                through="users.UserPersonalityTrait",
                to="users.personalitytrait",
            ),
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "discovery_radius_km",
                    models.PositiveIntegerField(default=10, help_text="Radius in km"),
                ),
                ("age_range_min", models.PositiveIntegerField(default=18)),
                ("age_range_max", models.PositiveIntegerField(default=99)),
                (
                    "min_trust_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("notify_nearby_activities", models.BooleanField(default=True)),
                ("notify_activity_invites", models.BooleanField(default=True)),
                ("notify_messages", models.BooleanField(default=True)),
                ("notify_friend_activities", models.BooleanField(default=True)),
                ("show_online_status", models.BooleanField(default=True)),
                ("allow_friend_requests", models.BooleanField(default=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User Preferences",
                "verbose_name_plural": "User Preferences",
                "db_table": "user_preferences",
            },
        ),
    ]
