# Generated by Django 5.0.9 on 2025-12-06 04:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ActivityCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                (
                    "icon",
                    models.CharField(help_text="Icon name/emoji for the category", max_length=50),
                ),
                (
                    "color",
                    models.CharField(default="#6366f1", help_text="Hex color code", max_length=7),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Activity Category",
                "verbose_name_plural": "Activity Categories",
                "db_table": "activity_categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Activity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "location_name",
                    models.CharField(
                        blank=True, help_text="Human-readable location name", max_length=255
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=500)),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                ("max_participants", models.PositiveIntegerField(default=10)),
                ("current_participants_count", models.PositiveIntegerField(default=0)),
                (
                    "visibility",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("private", "Private"),
                            ("friends", "Friends Only"),
                            ("invite", "Invite Only"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("full", "Full"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("min_age", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "min_trust_score",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=3,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "requirements",
                    models.TextField(blank=True, help_text="Additional requirements or notes"),
                ),
                ("cover_image", models.ImageField(blank=True, null=True, upload_to="activities/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_activities",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="activities",
                        to="activities.activitycategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "Activity",
                "verbose_name_plural": "Activities",
                "db_table": "activities",
                "ordering": ["-start_time"],
            },
        ),
        migrations.CreateModel(
            name="ActivityComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="activities.activity",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="activities.activitycomment",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_comments",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="ActivityParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("invited", "Invited"),
                            ("requested", "Requested to Join"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("checked_in", "Checked In"),
                            ("left", "Left"),
                        ],
                        default="requested",
                        max_length=20,
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="participants",
                        to="activities.activity",
                    ),
                ),
                (
                    "invited_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="sent_activity_invites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activity_participations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "activity_participants",
                "ordering": ["-joined_at"],
            },
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["latitude", "longitude"], name="activities_latitud_4beca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["start_time"], name="activities_start_t_7aa1a4_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["status"], name="activities_status_3f8f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["category"], name="activities_categor_19fdbd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "user")},
        ),
    ]
