# Generated by Django 5.0.9 on 2025-12-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("activities", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="activity",
            name="creator",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activity",
            name="category",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="activities",
                to="activities.activitycategory",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="replies",
                to="activities.activitycomment",
            ),
        ),
        migrations.AddField(
            model_name="activitycomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="activity",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="participants",
                to="activities.activity",
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="invited_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sent_activity_invites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="activityparticipant",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activity_participations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(
                fields=["latitude", "longitude"], name="activities_latitud_4beca2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["start_time"], name="activities_start_t_7aa1a4_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["status"], name="activities_status_3f8f9b_idx"),
        ),
        migrations.AddIndex(
            model_name="activity",
            index=models.Index(fields=["category"], name="activities_categor_19fdbd_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="activityparticipant",
            unique_together={("activity", "user")},
        ),
    ]
