# Generated by Django 5.0.9 on 2025-12-06 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="Accuracy in meters", null=True),
                ),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "current_activity",
                    models.CharField(
                        blank=True, help_text="What user is currently doing", max_length=200
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="locations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_locations",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["latitude", "longitude"], name="user_locati_latitud_ecfe0e_idx"
                    ),
                    models.Index(
                        fields=["is_current", "is_visible"], name="user_locati_is_curr_2d5704_idx"
                    ),
                    models.Index(fields=["-timestamp"], name="user_locati_timesta_90b952_idx"),
                ],
            },
        ),
    ]
