# Generated by Django 5.0.9 on 2025-12-06 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                (
                    "accuracy",
                    models.FloatField(blank=True, help_text="Accuracy in meters", null=True),
                ),
                ("altitude", models.FloatField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=True)),
                ("is_visible", models.BooleanField(default=True)),
                (
                    "current_activity",
                    models.CharField(
                        blank=True, help_text="What user is currently doing", max_length=200
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "user_locations",
                "ordering": ["-timestamp"],
            },
        ),
    ]
