# Generated by Django 5.0.9 on 2025-12-06 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("locations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="userlocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["latitude", "longitude"], name="user_locati_latitud_ecfe0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(
                fields=["is_current", "is_visible"], name="user_locati_is_curr_2d5704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userlocation",
            index=models.Index(fields=["-timestamp"], name="user_locati_timesta_90b952_idx"),
        ),
    ]
